name: Delete Old Releases and Tags

on:
  release:
    types: [published]
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    name: delete-old-releases
    steps:
      - name: Remove old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 4
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
