name: Delete Old Releases and Tags

on:
  release:
    types: [published]
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete old releases
        uses: Nats-ji/delete-old-releases@v1.0.1
        with:
          keep-count: 5
          remove-tags: true
          keep-old-minor-releases: true
          token: ${{ secrets.GITHUB_TOKEN }}
