name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Delete old releases
        if: success()
        uses: actions/delete-release@v1
        with:
          keep_latest: 4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
