name: Delete Old Releases and Tags

on:
  # Срабатывает при создании релиза вручную (через GitHub Releases)
  release:
    types: [published]
  
  # Срабатывает при любом коммите в main (или другой ветке)
  push:
    branches: [main]
  
  # Можно запустить вручную из Actions
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Удаляем старые релизы (оставляем 4 последних)
      - name: Delete old releases
        uses: dev-drprasad/delete-old-releases@v1.0.1
        with:
          keep_latest: 4   # Оставить 4 последних релиза
          delete_tag: true # Удаляет и теги тоже
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
