name: Clean Up Old Releases

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Delete old releases
        uses: dev-drprasad/delete-old-releases@v1.0.1
        with:
          keep_latest: 4
          delete_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
